### ISSUE TITLE
CBC validator rotation

### ISSUE THREAD

**Issue by yudetamago** [LayerXcom/cbc-casper-simulator#29]
We might implement the (mock of ?)`weight function` proposed in https://ethresear.ch/t/validator-rotation-in-cbc-casper/5200

**Comment by yudetamago** [comment]
mock
* uniform random number

**Comment by nrryuya** [comment]
I think validator rotation in other chain-based consensus is a relatively small problem so we can skip that for now.

**Comment by nrryuya** [comment]
so static weight mapping would be fine. I think uniform weight (i.e. w(v1) = w(v2) = ... = w(vn)) is simple and sufficient for now.

**Comment by yudetamago** [comment]
Finally, we now imported validator rotation functionality from https://github.com/nrryuya/cbc-validator-rotation.
Great thanks!
